### PR TITLE
README.md: add community links

### PR DESCRIPTION
**Pull request by oxapentane**
Add links to slack, discourse and mention IRC. Add a link to a centOS announcement.

Should make it easier to share the links to all the communication channels that are there atm.

### CODE REVIEW

**Review by hbjydev — APPROVED** [review]
Looks good to me.

**Comment by MarlonRacCambasis** [comment]
Perhaps mention the IRC channels on chat.freenode.net (`#rockylinux`, `#rockylinux-devel`, `#rockylinux-infra` and `#rockylinux-www`)

**Comment by danielmellado** [comment]
Sadly, after hearing all the news, LGTM

**Review by danielmellado — APPROVED** [review]

**Comment by oxapentane** [comment]
@MarlonRacCambasis there's a mention of `#rockylinux`, I think people can start from there. Plus as far as I understand we are migrating to https://github.com/rocky-linux/ org

**Comment by 12factor-mx** [comment]
Here ready to help

**Comment by jorp** [comment]
> @MarlonRacCambasis there's a mention of `#rockylinux`, I think people can start from there. Plus as far as I understand we are migrating to https://github.com/rocky-linux/ org. @gmkurtzer what's your opinion, maybe we should just put a link to the https://github.com/rocky-linux/organization/wiki/Contributing in this repo readme?

I think that would be a good idea. There's already some articles around the web linking here, and there's issues that are being opened and discussed on here, rather than https://github.com/rocky-linux/

**Pull request closed without merging**
